# rapid-router
#
# `make` on its own lists everything. The targets that talk to real
# providers source `.env` first (the binary has no dotenv of its own), so
# put provider keys there and they apply to `run`, `live` and the SDK
# suite alike.
#
# The `ci-*` targets mirror .github/workflows/ci.yml job for job — if one
# passes here it passes there, and `make ci` runs the lot.

.DEFAULT_GOAL := help
SHELL := /bin/bash

CARGO   ?= cargo
ENV_FILE ?= .env
CONFIG  ?=
PORT    ?=
# Project-local by default, deliberately. The gateway is managed-mode: it
# remembers the last config it was given, so a shared data dir means
# `make run` silently inherits state from whatever you ran days ago.
# Keeping it in-tree (and gitignored) makes a dev run reproducible and
# leaves ~/.rapidrouter — a real deployment's state — untouched.
DATA_DIR ?= .rapidrouter
# The dev gateway's config, generated on first use with a random admin
# key. It lives in DATA_DIR so it is gitignored and `make reset` clears
# it — a checked-in admin key is a credential in the repo.
DEV_CONFIG ?= $(DATA_DIR)/dev.toml
DEV_PORT ?= 8080
VITE_PORT ?= 5173
# Overridable so `make live-subs MODEL=…` can pin a model.
MODEL   ?= claude-sonnet-4-5-20250929

# Provider keys live in .env, which is gitignored. Sourced rather than
# `include`d: include chokes on quoted values and would export comments.
# `.` searches PATH for a bare name, so a relative ENV_FILE is anchored to
# the tree explicitly; an absolute one is passed through untouched.
LOAD_ENV = if [ -f "$(ENV_FILE)" ]; then \
             case "$(ENV_FILE)" in /*) _e="$(ENV_FILE)";; *) _e="./$(ENV_FILE)";; esac; \
             set -a; . "$$_e"; set +a; \
           fi

RUN_FLAGS = --data-dir $(DATA_DIR) \
            $(if $(CONFIG),--config $(CONFIG)) \
            $(if $(PORT),--port $(PORT))

.PHONY: help
help: ## List every target
	@awk 'BEGIN {FS = ":.*?## "} \
	     /^## /      {printf "\n\033[1m%s\033[0m\n", substr($$0, 4)} \
	     /^[a-zA-Z0-9_-]+:.*?## / {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}' \
	     $(MAKEFILE_LIST)
	@echo

## Run
.PHONY: dev
# The dev config is *imported* rather than passed with `--config`: in
# managed mode a config file only seeds an empty store, so once a store
# exists the file is ignored — and an ignored file means the admin key
# printed below would not be the one that works.
dev: dev-config console-deps ## Gateway + Vite together, with the admin key printed
	@$(MAKE) --no-print-directory admin-key
	@echo "  Console (hot reload): http://127.0.0.1:$(VITE_PORT)/console/"
	@echo "  Gateway:              http://127.0.0.1:$(DEV_PORT)"
	@echo
	@$(LOAD_ENV); \
	 $(CARGO) run -q -p router-bin -- --data-dir $(DATA_DIR) config import $(DEV_CONFIG); \
	 $(CARGO) run -q -p router-bin -- --dev --data-dir $(DATA_DIR) --port $(DEV_PORT) & \
	 gateway=$$!; \
	 trap 'kill $$gateway 2>/dev/null; wait $$gateway 2>/dev/null; exit 0' INT TERM EXIT; \
	 until curl -sf http://127.0.0.1:$(DEV_PORT)/health >/dev/null 2>&1; do \
	   kill -0 $$gateway 2>/dev/null || { echo "gateway exited before it was ready"; exit 1; }; \
	   sleep 1; \
	 done; \
	 RAPID_GATEWAY=http://127.0.0.1:$(DEV_PORT) npm --prefix console run dev -- --host 127.0.0.1 --port $(VITE_PORT)

.PHONY: dev-config
dev-config: ## Create the dev config with a fresh admin key, if absent
	@mkdir -p $(DATA_DIR)
	@test -f $(DEV_CONFIG) || { \
	  key=$$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'); \
	  printf '%s\n' \
	    '# Generated by `make dev`. Gitignored — the admin key is a credential.' \
	    '[server]' \
	    'host = "127.0.0.1"' \
	    'port = $(DEV_PORT)' \
	    '' \
	    '[console]' \
	    "admin_keys = [\"$$key\"]" \
	    '' \
	    '# No providers yet — add them from the console (Providers -> Add' \
	    '# provider), or list them here. Note that once this file exists,' \
	    '# zero-config discovery from .env no longer applies.' > $(DEV_CONFIG); \
	  echo "created $(DEV_CONFIG)"; \
	}

.PHONY: admin-key
admin-key: dev-config ## Print the dev console admin key
	@echo
	@echo "  Admin key: $$(grep -o '\"[0-9a-f]\{48\}\"' $(DEV_CONFIG) | tr -d '\"')"

.PHONY: console-deps
console-deps:
	@test -d console/node_modules || npm --prefix console ci

.PHONY: run
run: ## Start the gateway on :8080 with human-readable logs (CONFIG=, PORT=)
	@$(LOAD_ENV); $(CARGO) run -p router-bin -- --dev $(RUN_FLAGS)

.PHONY: run-release
run-release: ## Start the optimized build — use this for anything perf-related
	@$(LOAD_ENV); $(CARGO) run --release -p router-bin -- --dev $(RUN_FLAGS)

.PHONY: check-config
check-config: ## Validate a config and exit: make check-config CONFIG=subs.toml
	@test -n "$(CONFIG)" || { echo "set CONFIG=<file>"; exit 2; }
	@$(LOAD_ENV); $(CARGO) run -q -p router-bin -- check $(CONFIG)

.PHONY: build
build: ## Debug build
	$(CARGO) build --workspace

.PHONY: release
release: ## Optimized build
	$(CARGO) build --release -p router-bin

## Check
.PHONY: test
test: ## Whole workspace test suite
	$(CARGO) test --workspace

.PHONY: fmt
fmt: ## Format in place
	$(CARGO) fmt --all

.PHONY: lint
lint: ## Clippy over every target, warnings denied (as CI does)
	RUSTFLAGS="-D warnings" $(CARGO) clippy --workspace --all-targets

.PHONY: e2e
e2e: ## Account ownership over real HTTP, against a recording fake vendor
	$(CARGO) build -p router-bin
	scripts/e2e/run.sh

.PHONY: e2e-hold
e2e-hold: ## Same, but leave the gateway up so the real agent CLIs can drive it
	$(CARGO) build -p router-bin
	scripts/e2e/run.sh --hold

.PHONY: verify
verify: ## fmt check + lint + test — run before pushing
	$(CARGO) fmt --all --check
	RUSTFLAGS="-D warnings" $(CARGO) clippy --workspace --all-targets
	$(CARGO) test --workspace

## CI jobs (mirror .github/workflows/ci.yml)
.PHONY: ci
ci: verify ci-control-plane ci-loom ci-console ci-sdk-suite ci-perf ## Every CI job except audit and the live suites

.PHONY: ci-control-plane
ci-control-plane: ## Store backends, store facade, fleet behaviour
	$(CARGO) test -p router-store --test backends --release
	$(CARGO) test -p router-store --test store --release
	$(CARGO) test -p router-server --test fleet --release

.PHONY: ci-loom
ci-loom: ## Model-check the breaker and token bucket under loom
	RUSTFLAGS="--cfg loom" $(CARGO) test -p router-core --test loom_models --release

.PHONY: ci-sdk-suite
ci-sdk-suite: ## Official OpenAI/Anthropic SDKs against gateway + mock
	@python3 -m venv /tmp/rapid-sdkvenv
	@/tmp/rapid-sdkvenv/bin/pip install --quiet --upgrade openai anthropic
	scripts/sdk-suite/run.sh /tmp/rapid-sdkvenv/bin/python

.PHONY: ci-perf
ci-perf: ## Benches compile, overhead gate, short soak
	$(CARGO) bench --workspace -- --test
	$(CARGO) run --release -p rig -- overhead --rps 200 --secs 5 --assert-p50-us 400 --assert-p99-us 4000
	$(CARGO) run --release -p rig -- soak --secs 20 --rps 100 --assert-rss-growth-pct 40

.PHONY: audit
audit: ## cargo-audit over the dependency tree
	$(CARGO) audit

## Console (console/)
.PHONY: console-dev
console-dev: console-deps ## Vite alone, against a gateway you started yourself
	RAPID_GATEWAY=http://127.0.0.1:$(DEV_PORT) npm --prefix console run dev -- --host 127.0.0.1 --port $(VITE_PORT)

.PHONY: console-build
console-build: ## Typecheck and build the console bundle
	cd console && npm ci && npm run typecheck && npm run build

.PHONY: ci-console
ci-console: console-build ## Console build, e2e, and bundle budget
	cd console && npx playwright install --with-deps chromium && npm run test:e2e && npm run budget
	$(CARGO) build -p router-server --no-default-features

## Live providers (spends real quota)
.PHONY: live
live: ## Conformance shapes against real provider APIs; skips per missing key
	@$(LOAD_ENV); $(CARGO) test -p router-server --test live_validation -- --ignored --nocapture

.PHONY: live-subs
live-subs: ## Subscription seats against real backends (MODEL= to pin one)
	@$(LOAD_ENV); \
	 if [ -z "$$LIVE_CLAUDE_SUBSCRIPTION_TOKEN" ] && [ -z "$$LIVE_CODEX_AUTH_JSON" ]; then \
	   echo "Set LIVE_CLAUDE_SUBSCRIPTION_TOKEN (see 'make setup-token') and/or"; \
	   echo "LIVE_CODEX_AUTH_JSON=\$$HOME/.codex/auth.json, in $(ENV_FILE) or the environment."; \
	   exit 2; \
	 fi; \
	 LIVE_CLAUDE_SUBSCRIPTION_MODEL="$(MODEL)" \
	   $(CARGO) test -p router-server --test live_subscriptions -- --ignored --nocapture

.PHONY: setup-token
setup-token: ## Mint a 1-year Claude subscription token (interactive, opens a browser)
	@echo "Running 'claude setup-token'. Put the printed sk-ant-oat01-… into $(ENV_FILE) as:"
	@echo "  LIVE_CLAUDE_SUBSCRIPTION_TOKEN=sk-ant-oat01-…"
	@echo
	@claude setup-token

## Housekeeping
.PHONY: reset
reset: ## Forget the local gateway state (config, keys, usage) in $(DATA_DIR)
	@rm -rf $(DATA_DIR)
	@echo "cleared $(DATA_DIR)"

.PHONY: clean
clean: ## Remove all build output
	$(CARGO) clean

.PHONY: clean-incremental
clean-incremental: ## Drop the incremental cache only — the usual disk hog
	@du -sh target/debug/incremental 2>/dev/null || true
	@rm -rf target/debug/incremental
	@echo "incremental cache cleared"
