[package]
name = "rig"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rig"
path = "src/main.rs"

[dependencies]
router-core = { workspace = true }
router-server = { workspace = true }
mock-provider = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
hdrhistogram = { workspace = true }
mimalloc = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
